name: Build and push TypeScript
on: 
    push: 
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Build and push
              uses: alexthemaster/action-build-typescript@v1.3.1
              with:
                pushToBranch: true
                branch: 'master' 
                githubToken: ${{ secrets.GITHUB_TOKEN }} 
